{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "ec5ea689",
   "metadata": {},
   "source": [
    "### Tratamento de Exceções em Python\n",
    "\n",
    "O tratamento de exceções é uma parte crucial da programação robusta e resiliente. Exceções permitem que você lide com erros de forma controlada e previsível, mantendo a integridade e a estabilidade do programa. \n",
    "\n",
    "#### Principais Tipos de Exceções\n",
    "\n",
    "Python possui várias exceções internas que cobrem uma ampla gama de erros. Aqui estão algumas das principais exceções:\n",
    "\n",
    "1. **BaseException**: A classe base para todas as exceções.\n",
    "2. **Exception**: A classe base para todas as exceções que podem ser capturadas pelo usuário.\n",
    "3. **ArithmeticError**: Classe base para erros numéricos, como `ZeroDivisionError`.\n",
    "4. **AttributeError**: Levantada quando um atributo de objeto não é encontrado.\n",
    "5. **EOFError**: Levantada quando a função `input()` atinge o final do arquivo sem ler nenhum dado.\n",
    "6. **ImportError**: Levantada quando uma importação falha.\n",
    "7. **IndexError**: Levantada quando um índice de sequência está fora do intervalo.\n",
    "8. **KeyError**: Levantada quando uma chave de dicionário não é encontrada.\n",
    "9. **KeyboardInterrupt**: Levantada quando o usuário interrompe a execução do programa, geralmente pressionando `Ctrl+C`.\n",
    "10. **MemoryError**: Levantada quando uma operação não pode ser concluída devido à falta de memória.\n",
    "11. **NameError**: Levantada quando uma variável local ou global não é encontrada.\n",
    "12. **OSError**: Classe base para erros do sistema operacional.\n",
    "13. **OverflowError**: Levantada quando um cálculo excede o limite máximo para um tipo numérico.\n",
    "14. **RuntimeError**: Levantada quando um erro gerado não pertence a nenhuma categoria específica.\n",
    "15. **StopIteration**: Levantada para sinalizar o final de uma iteração.\n",
    "16. **SyntaxError**: Levantada quando a análise do código fonte falha.\n",
    "17. **TypeError**: Levantada quando uma operação ou função é aplicada a um objeto de tipo inadequado.\n",
    "18. **ValueError**: Levantada quando uma função recebe um argumento com o tipo correto, mas com um valor inapropriado.\n",
    "19. **ZeroDivisionError**: Levantada quando a segunda operando de uma divisão ou módulo é zero.\n",
    "\n",
    "#### Árvore de Exceções\n",
    "\n",
    "A hierarquia das exceções em Python é organizada em uma árvore, com `BaseException` no topo. Aqui está uma visão simplificada da árvore de exceções:\n",
    "\n",
    "```\n",
    "BaseException\n",
    "├── SystemExit\n",
    "├── KeyboardInterrupt\n",
    "├── GeneratorExit\n",
    "└── Exception\n",
    "    ├── ArithmeticError\n",
    "    │   ├── FloatingPointError\n",
    "    │   ├── OverflowError\n",
    "    │   └── ZeroDivisionError\n",
    "    ├── AssertionError\n",
    "    ├── AttributeError\n",
    "    ├── BufferError\n",
    "    ├── EOFError\n",
    "    ├── ImportError\n",
    "    │   └── ModuleNotFoundError\n",
    "    ├── LookupError\n",
    "    │   ├── IndexError\n",
    "    │   └── KeyError\n",
    "    ├── MemoryError\n",
    "    ├── NameError\n",
    "    │   └── UnboundLocalError\n",
    "    ├── OSError\n",
    "    │   ├── BlockingIOError\n",
    "    │   ├── ChildProcessError\n",
    "    │   ├── ConnectionError\n",
    "    │   │   ├── BrokenPipeError\n",
    "    │   │   ├── ConnectionAbortedError\n",
    "    │   │   ├── ConnectionRefusedError\n",
    "    │   │   └── ConnectionResetError\n",
    "    │   ├── FileExistsError\n",
    "    │   ├── FileNotFoundError\n",
    "    │   ├── InterruptedError\n",
    "    │   ├── IsADirectoryError\n",
    "    │   ├── NotADirectoryError\n",
    "    │   ├── PermissionError\n",
    "    │   ├── ProcessLookupError\n",
    "    │   └── TimeoutError\n",
    "    ├── ReferenceError\n",
    "    ├── RuntimeError\n",
    "    │   ├── NotImplementedError\n",
    "    │   └── RecursionError\n",
    "    ├── StopIteration\n",
    "    ├── StopAsyncIteration\n",
    "    ├── SyntaxError\n",
    "    │   └── IndentationError\n",
    "    │       ├── TabError\n",
    "    ├── SystemError\n",
    "    ├── TypeError\n",
    "    ├── ValueError\n",
    "    │   └── UnicodeError\n",
    "    │       ├── UnicodeDecodeError\n",
    "    │       ├── UnicodeEncodeError\n",
    "    │       └── UnicodeTranslateError\n",
    "    └── Warning\n",
    "        ├── DeprecationWarning\n",
    "        ├── PendingDeprecationWarning\n",
    "        ├── RuntimeWarning\n",
    "        ├── SyntaxWarning\n",
    "        ├── UserWarning\n",
    "        ├── FutureWarning\n",
    "        ├── ImportWarning\n",
    "        ├── UnicodeWarning\n",
    "        └── BytesWarning\n",
    "```\n",
    "\n",
    "#### Criação de Exceções Personalizadas\n",
    "\n",
    "Para criar as próprias exceções personalizadas em Python basta derivar da classe `Exception` ou de qualquer uma de suas subclasses.\n",
    "\n",
    "##### Exemplo de Exceção Personalizada\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "01f0f77c",
   "metadata": {},
   "outputs": [],
   "source": [
    "class MinhaExcecaoPersonalizada(Exception):\n",
    "    def __init__(self, mensagem, codigo_erro):\n",
    "        super().__init__(mensagem)\n",
    "        self.codigo_erro = codigo_erro\n",
    "\n",
    "try:\n",
    "    raise MinhaExcecaoPersonalizada(\"Algo deu errado\", 500)\n",
    "except MinhaExcecaoPersonalizada as e:\n",
    "    print(f\"Erro: {e}, Código de erro: {e.codigo_erro}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "44f073c3",
   "metadata": {},
   "source": [
    "\n",
    "#### Lançamento e Captura de Exceções\n",
    "\n",
    "Em Python, é possível lançar exceções usando a palavra-chave `raise` e capturar exceções usando blocos `try-except`.\n",
    "\n",
    "##### Lançamento de Exceções\n",
    "\n",
    "Usar `raise` para lançar exceções:\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b83b8287",
   "metadata": {},
   "outputs": [],
   "source": [
    "def dividir(a, b):\n",
    "    if b == 0:\n",
    "        raise ZeroDivisionError(\"Divisão por zero não é permitida\")\n",
    "    return a / b\n",
    "\n",
    "try:\n",
    "    resultado = dividir(10, 0)\n",
    "except ZeroDivisionError as e:\n",
    "    print(e)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ed700f7c",
   "metadata": {},
   "source": [
    "\n",
    "##### Captura de Exceções\n",
    "\n",
    "Use blocos `try-except` para capturar exceções e lidar com elas:\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a210cec6",
   "metadata": {},
   "outputs": [],
   "source": [
    "try:\n",
    "    resultado = 10 / 0\n",
    "except ZeroDivisionError:\n",
    "    print(\"Erro: Divisão por zero\")\n",
    "except Exception as e:\n",
    "    print(f\"Erro inesperado: {e}\")\n",
    "else:\n",
    "    print(f\"Resultado: {resultado}\")\n",
    "finally:\n",
    "    print(\"Execução do bloco finally\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "cd4b3181",
   "metadata": {},
   "source": [
    "\n",
    "Neste exemplo:\n",
    "- O bloco `try` contém código que pode gerar exceções.\n",
    "- Os blocos `except` capturam e lidam com exceções específicas.\n",
    "- O bloco `else` é executado se nenhuma exceção for lançada.\n",
    "- O bloco `finally` é sempre executado, independentemente de uma exceção ter sido lançada ou não.\n",
    "\n",
    "### Vantagens do Tratamento de Exceções\n",
    "\n",
    "1. **Robustez**: Permite que o programa lide com erros de forma controlada, aumentando a robustez.\n",
    "2. **Manutenção**: Facilita a manutenção do código, permitindo que erros sejam capturados e tratados adequadamente.\n",
    "3. **Debugging**: Melhora a capacidade de debugging, fornecendo informações detalhadas sobre onde e por que ocorreu um erro.\n",
    "\n",
    "### Considerações\n",
    "\n",
    "1. **Performance**: Capturar exceções pode ser mais lento do que verificar condições de erro antecipadamente. Use exceções para condições verdadeiramente excepcionais.\n",
    "2. **Legibilidade**: Exceções personalizadas devem ser usadas de maneira que melhorem a clareza e a legibilidade do código.\n",
    "\n",
    "### Resumo\n",
    "\n",
    "- **Tipos de Exceções**: Python possui uma vasta hierarquia de exceções internas, organizadas em uma árvore de exceções.\n",
    "- **Criação de Exceções Personalizadas**: Permite que você defina suas próprias exceções para lidar com casos de erro específicos.\n",
    "- **Lançamento de Exceções**: Use `raise` para lançar exceções quando ocorrerem erros.\n",
    "- **Captura de Exceções**: Use blocos `try-except` para capturar e tratar exceções, garantindo que o programa lide com erros de forma controlada.\n",
    "\n",
    "Compreender e utilizar eficazmente o tratamento de exceções é essencial para escrever programas robustos, seguros e fáceis de manter.\n"
   ]
  }
 ],
 "metadata": {},
 "nbformat": 4,
 "nbformat_minor": 5
}
